### ISSUE TITLE
Fix validator test with skipped accounts

### ISSUE THREAD

**Issue by shadowinek** [mensler/bav#8]
There are some validator tests, that have skipped test. 

Expectation is mostly, that the false examples for some variants are valid for other variants

- Validator51
- ValidatorA4
- ValidatorB5
- ValidatorB8
- ValidatorD3

**Comment by mensler** [comment]
You're right. The examples in the pruefziffernberechnungsmethoden document are separated by variant, so often the same account number is stated as invalid for the first variant but valid for the second.
That's why I splitted the test data blocks by valid account numbers per variant and wrong ones: https://github.com/mensler/bav/blob/master/tests/unit/validators/ValidatorE4Test.php#L38

**Comment by shadowinek** [comment]
I am currently working on this ticket and trying to confirm that those are these cases and possibly move the tests under the variants where they are correct.
